### ISSUE TITLE
Copycat? 

### ISSUE THREAD

**Issue by danklotz** [GuillaumePressiat/stringfix#2]
Such a package has already been proposed before. I think it should at least be attributed: 

- https://chrisschuerz.github.io/projects/pasta/
- https://cran.r-project.org/src/contrib/Archive/pasta/
- https://github.com/chrisschuerz/pasta

**Comment by GuillaumePressiat** [comment]
Hi,

Copycat? Really? No. Man can only copy what he knows exist.
Thanks for your remark. I didn't know this package. I will add a reference to this `pasta` existing package or maybe study possibilities to import functions from it. 

I suggest you read `stringfix`'s man pages because this package contains other functions which are not in `pasta` package :

- [%s%](https://guillaumepressiat.github.io/stringfix/reference/grapes-s-grapes.html) substr alias
- [%gic%](https://guillaumepressiat.github.io/stringfix/reference/grapes-gic-grapes.html) grepl alias
- [%pad%](https://guillaumepressiat.github.io/stringfix/reference/grapes-pad-grapes.html) pad alias
- See [here](https://guillaumepressiat.github.io/stringfix/reference/index.html) all functions.

And in other way `pasta` package contains functions that are not in `stringfix`. `pasta` seems to contain only functions for pasting like its name says it. `stringfix` contains only three functions for pasting on a total of twenty.

This package is first for my personal use but also seems to be for people suggesting an unknown guy is a copycat!
